services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    runtime: python
    region: oregon
    pythonVersion: 3.10
